services:
  hello-docker-ubuntu-dev:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
    image: hello-docker-ubuntu:latest  # 构建后镜像的名称和标签，建议和项目绑定，否则和其他项目冲突
    restart: unless-stopped # 重启策略
    environment:
      APP_NAME: "hello-docker"
      # -- mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root_secret_password}
      MYSQL_DATABASE: default_db
      MYSQL_USER: myuser
      MYSQL_PASSWORD: my_secret_password
      # -- nvidia-docker
      # NVIDIA_VISIBLE_DEVICES: all
      # NVIDIA_DRIVER_CAPABILITIES: all
    volumes:
      - ".:/root/hello-docker"
      - "~/.ssh:/root/.ssh:ro" # 挂载宿主机的ssh配置文件，方便推拉代码（只读）
      - "/etc/localtime:/etc/localtime:ro" # 挂载宿主机时间到容器
    working_dir: /root/hello-docker
    networks:
      - default
    # -- 端口映射
    ports:          
      - "8080:8080" 
    # runtime: nvidia  # 使用 nvidia-docker
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - capabilities: [gpu]
    # -- sleep infinity 用于保持容器运行，否则 vscode 无法进入容器
    command: ["sleep", 'infinity']

  mysql-server:
    image: mysql:latest # https://hub.docker.com/_/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root_secret_password}
      MYSQL_DATABASE: default_db
      MYSQL_USER: myuser
      MYSQL_PASSWORD: my_secret_password
      TZ: Asia/Shanghai # 设置时区
    ports:
      - "3306:3306"
    networks:
      - default
    volumes:
      - mysql_data:/var/lib/mysql
      # - ./sql/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql  # 初始化数据库脚本
      # - ./sql/mysql/sql:/opt/sql  # 初始化数据库脚本

  redis-server:
    image: redis:latest # https://hub.docker.com/_/redis
    ports:
      - "6379:6379"
    networks:
      - default
  etcd-server:
    image: bitnami/etcd:latest
    ports:
      - "2379:2379" # 2379 用于客户端与 etcd 通信
      - "2380:2380" # 2380 用于 etcd 节点之间的通信
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes # 允许无认证访问 etcd，适用于开发和测试环境。在生产环境中，建议配置认证机制
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379 # 指定 etcd 向客户端公开的 URL，这里使用了服务名 etcd，以便在 Docker 网络中进行通信
    networks:
      - default
    # volumes:
    #   - /path/to/etcd-data:/bitnami/etcd/data # 挂载本地的 /path/to/etcd-data 目录 数据持久化

  # Elasticsearch
  elasticsearch-server:
    image: bitnami/elasticsearch:latest # https://hub.docker.com/r/bitnami/elasticsearch
    environment:
      - discovery.type=single-node
    networks:
      - default
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  # Milvus 单机版(standalone)
  milvus-standalone:
    image: milvusdb/milvus:v2.5.4 # https://hub.docker.com/r/milvusdb/milvus
    platform: linux/amd64  # milvus docker 貌似暂时没支持 arm64
    command: ["milvus", "run", "standalone"]
    security_opt:
    - seccomp:unconfined
    environment:
      ETCD_ENDPOINTS: milvus-etcd:2379
      MINIO_ADDRESS: milvus-minio:9000
    depends_on:
      - "milvus-etcd"
      - "milvus-minio"
    ports:
      - "19530:19530"
      - "9091:9091"
    networks:
      - default
    volumes:
      - milvus_data:/var/lib/milvus
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
  
  # Milvus 依赖的 Etcd
  milvus-etcd:
    image: quay.io/coreos/etcd:v3.5.16
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    networks:
      - default
    volumes:
      - milvus_etcd_data:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 20s
      retries: 3

  # Milvus 依赖的 Minio
  milvus-minio:
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9001:9001"
      - "9000:9000"
    volumes:
      - milvus_minio_data:/minio_data
    command: minio server /minio_data --console-address ":9001"
    networks:
      - default
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  
  # Milvus 的可视化管理工具 Attu
  milvus-attu:
    image: zilliz/attu:v2.4
    environment:
      MILVUS_URL: milvus-standalone:19530
    ports:
      - "8000:3000" # 访问地址 http://localhost:8000
    depends_on:
      - "milvus-standalone"
    networks:
      - default

      
# -- 网络名称，用于容器间通信
networks:
  default:
    name: hello-docker-network
  

# -- 数据卷名称，用于持久化数据
volumes:
  mysql_data:
  elasticsearch_data:
  milvus_data:  # 添加Milvus的数据卷
  milvus_etcd_data:  # 添加Milvus的Etcd数据卷
  milvus_minio_data:  # 添加Milvus的Minio数据卷