# Get the base image
FROM ubuntu:noble

# Set the locale
# RUN apt-get update \
# 	&& apt-get install -y locales \
# 	&& rm -rf /var/lib/apt/lists/* \
# 	&& localedef -i zh_CN -c -f UTF-8 -A /usr/share/locale/locale.alias zh_CN.UTF-8
# ENV LANG zh_CN.utf8